name: k8s-pod-delete
identity: k8spoddelete
kind: ChaosExperimentTemplate
apiVersion: litmuschaos.io/v1beta1
spec:
  infraType: KubernetesV2
  faults:
    - name: pod-delete
      identity: pod-delete
      revision: "1"
      isEnterprise: true
      values:
        - name: TARGET_CONTAINER
          value: ""
        - name: NODE_LABEL
          value: ""
        - name: PODS_AFFECTED_PERC
          value: <+input>
        - name: TARGET_WORKLOAD_KIND
          value: <+input>
        - name: TARGET_WORKLOAD_NAMESPACE
          value: <+input>
        - name: TARGET_WORKLOAD_NAMES
          value: <+input>
        - name: POD_AFFECTED_PERCENTAGE
          value: "100"
        - name: SEQUENCE
          value: parallel
        - name: TOTAL_CHAOS_DURATION
          value: 60
  probes:
    - name: nobl9-probe-grk
      identity: nobl9-errorbudgetremainingpercentage
      isEnterprise: false
      weightage: 10
      duration: 30s
      enableDataCollection: false
      values: []
    - name: nobl9-probe-ban
      identity: nobl9-errorbudgetremainingpercentage
      isEnterprise: false
      weightage: 10
      duration: 30s
      enableDataCollection: false
      values: []
  actions:
    - name: delay-120s-ijg
      identity: delay-30s
      isEnterprise: false
      continueOnCompletion: false
      values: []
    - name: delay-120s-vng
      identity: delay-30s
      isEnterprise: false
      continueOnCompletion: false
      values: []
  vertices:
    - name: v-probe
      start:
        probes:
          - name: nobl9-probe-grk
      end: {}
    - name: v-d1
      start:
        actions:
          - name: delay-120s-ijg
      end:
        probes:
          - name: nobl9-probe-grk
    - name: v-start
      start:
        faults:
          - name: pod-delete
      end:
        actions:
          - name: delay-120s-ijg
    - name: v-d2
      start:
        actions:
          - name: delay-120s-vng
      end:
        faults:
          - name: pod-delete
    - name: v-7xj
      start:
        probes:
          - name: nobl9-probe-ban
      end:
        actions:
          - name: delay-120s-vng
    - name: v-end
      start: {}
      end:
        probes:
          - name: nobl9-probe-ban
  cleanupPolicy: delete
variables:
  - name: N9_SLO_NAME
    value: <+input>
    type: String
    required: false
  - name: N9_SLO_PROJECT
    value: <+input>
    type: String
    required: false
  - name: N9_SLO_OBJECTIVE
    value: <+input>
    type: String
    required: false
revision: v1
isDefault: true
