name: pod-delete

identity: poddelete

kind: ChaosExperimentTemplate

apiVersion: litmuschaos.io/v1beta1

spec:

    infraType: KubernetesV2

    faults:

        - name: pod-delete-9nn

          identity: pod-delete

          revision: v1

          isEnterprise: true

          values:

            - name: TARGET_WORKLOAD_KIND

              value: deployment

            - name: TARGET_WORKLOAD_NAMESPACE

              value: <+input>

            - name: TARGET_WORKLOAD_NAMES

              value: <+input>

            - name: TOTAL_CHAOS_DURATION

              value: 90

            - name: CHAOS_INTERVAL

              value: 90

          authEnabled: false

    probes:

        - name: nobl9-probe-hwf

          identity: nobl9-errorbudgetremainingpercentage

          isEnterprise: false

          weightage: 10

          duration: 30s

          enableDataCollection: false

          values:

            - name: N9_SLO_NAME

              value: <+experiment.variables.N9_SLO_NAME>

            - name: N9_SLO_PROJECT

              value: <+experiment.variables.N9_SLO_PROJECT>

            - name: N9_SLO_OBJECTIVE

              value: <+experiment.variables.N9_SLO_OBJECTIVE>

            - name: COMPARATOR_VALUE

              value: <+experiment.variables.N9_ERROR_BUDGET_THRESHOLD>

    actions:

        - name: delay-120s-yz1

          identity: delay-30s

          isEnterprise: false

          continueOnCompletion: false

          values: []

    vertices:

        - name: v-hmx

          start:

            faults:

                - name: pod-delete-9nn

          end: {}

        - name: v-z43

          start:

            actions:

                - name: delay-120s-yz1

          end:

            faults:

                - name: pod-delete-9nn

        - name: v-hyg

          start:

            probes:

                - name: nobl9-probe-hwf

          end:

            actions:

                - name: delay-120s-yz1

        - name: v-end

          start: {}

          end:

            probes:

                - name: nobl9-probe-hwf

    cleanupPolicy: delete

variables:

    - name: N9_SLO_NAME

      value: <+input>

      type: String

      description: For Nobl9 SLO Name

      required: true

    - name: N9_SLO_PROJECT

      value: <+input>

      type: String

      description: For nobl9 project

      required: true

    - name: N9_SLO_OBJECTIVE

      value: <+input>

      type: String

      description: For Nobl9 SLO objective

      required: true

    - name: N9_ERROR_BUDGET_THRESHOLD

      value: <+input>

      type: String

      required: false

revision: v1

isDefault: true

